version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes: 
      - polls_pg_data:/bitnami/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  polls_pg_data: